### PR TITLE
Add support for --dry-run

### PR DESCRIPTION
**Pull request by chalin**
Made **minimal** changes to support performing a dry run. As shown by the sample output below, descriptions of the steps are followed by the exact commands executed (lines prefixed with `>`).

Given the level of detail in the output, support for `--dry-run` was only added to `dart_doc_syncer` and not `sync_all`.

(The new `options.dart` file is a bit long but it was just as easy to borrow `ArgParser` usage code from elsewhere than to hand craft the processing.)

```
Cloning https://github.com/angular/angular.io into ~/git/dart-doc-syncer/bin/.tmp/angular_io.
  > git clone https://github.com/angular/angular.io ~/git/dart-doc-syncer/bin/.tmp/angular_io
Cloning git@github.com:angular-examples/architecture.git into ~/git/dart-doc-syncer/bin/.tmp/architecture.
  > git clone git@github.com:angular-examples/architecture.git ~/git/dart-doc-syncer/bin/.tmp/architecture
Deleting all the repository content in ~/git/dart-doc-syncer/bin/.tmp/architecture.
  > git rm * (~/git/dart-doc-syncer/bin/.tmp/architecture)
Generating updated example application into ~/git/dart-doc-syncer/bin/.tmp/architecture.
  > cp -a ~/git/dart-doc-syncer/bin/../default_assets/. ~/git/dart-doc-syncer/bin/.tmp/architecture
  > cp -a ~/git/dart-doc-syncer/bin/.tmp/angular_io/public/docs/_examples/architecture/dart/. ~/git/dart-doc-syncer/bin/.tmp/architecture
  > rm ~/git/dart-doc-syncer/bin/.tmp/architecture/.analysis_options
  > cp ~/git/dart-doc-syncer/bin/.tmp/angular_io/public/docs/_examples/styles.css ~/git/dart-doc-syncer/bin/.tmp/architecture/web/styles.css
Removing doc tags in ~/git/dart-doc-syncer/bin/.tmp/architecture.
Running dartfmt in ~/git/dart-doc-syncer/bin/.tmp/architecture.
  > dartfmt -w ~/git/dart-doc-syncer/bin/.tmp/architecture
Checkout master.
  > git checkout master (~/git/dart-doc-syncer/bin/.tmp/architecture)
Staging local changes for ~/git/dart-doc-syncer/bin/.tmp/architecture.
  > git add . (~/git/dart-doc-syncer/bin/.tmp/architecture)
Comitting changes for ~/git/dart-doc-syncer/bin/.tmp/architecture.
  > git commit -m Sync with null
```

### CODE REVIEW

**Comment by thso** [comment]
LGTM

**Comment by kwalrath** [comment]
While I like this change (except "Comitting" should be "Committing"!), I'd also like a less verbose version, which could be used for both dart_doc_syncer and sync_all.

Sometimes I just want to know which repos (and which branches of the repos) will be updated.

**Comment by thso** [comment]
I vote to keep Comitting!

**Comment by thso** [comment]
But a less verbose version is on my list, no worries!

**Comment by chalin** [comment]
Right, I've seen the other two open PRs for the two issues that you mention. I can address them in the next little while if you like (but I'd like to get some angular.io commits in first :).

**Comment by chalin** [comment]
Oh, did you mean that you want the dart_doc_syncer `--dry-run` to be less verbose? I think that less verbosity for `sync_all` makes sense, but I'm not sure how useful it would be to tone it down for `dart_doc_syncer`. Anyhow, we can discuss offline.

**Comment by kwalrath** [comment]
I'm not sure. :) The existing output might be fine for dart_doc_syncer. But if it's easy to do a less verbose version, that'd be nice to have.

**Pull request merged**
