### PR TITLE
Build app w/o tests; use webdev tool

### PR DESCRIPTION
**Pull request by chalin**
Contributes to https://github.com/dart-lang/site-webdev/issues/1610.

cc @kwalrath

### CODE REVIEW

**Comment by chalin** [comment]
@thso - friendly ping.

**Comment by chalin** [comment]
@kevmoo - mind reviewing this PR?

**Review by kevmoo — APPROVED** [review]
I have zero context. Approving because travis is green.

**Comment by chalin** [comment]
@thso - I'll merge now; feel free to offer feedback later anyways.

**Pull request merged**
